Illustrates a 12K config in a 16K image
SamCoVT/TaliForth2 pull request #42
Opened 2024-03-12 23:56 UTC by patricksurry

Makes disassembler an optional word, and strips out some strings to create a workable py65mon image in $c000-$efff

Also corrects a couple of typos, and updates some comments/memmap picture in py65mon config to match the defs.

2024-03-16 02:03 UTC, SamCoVT requested changes
Having a smaller Tali has been requested several times, so I think this is a good idea.  I don't like removing `see` along with the disassembler, but if you _really_ need those last few bytes you could create a separate config word for removing it.  

I also don't like having special behavior triggered by an empty config word set, but am generally fine with adding extra config words for items you might want to remove.  Just add a description of them in the platform/platform-py65mon.asm file as that is the official keeper of them and make sure they default to "assembled" at the top of taliforth.asm.

2024-03-16 02:03 UTC, SamCoVT commented on disassembler.asm
>  oc_index_table:
This table is also used by the assembler and can only be removed when neither "assembler" nor "disassembler" are in the options.  This is also true for the table that follows.

2024-03-16 02:03 UTC, SamCoVT commented on headers.asm
>  nt_see: .byte 3, NN
While `see` uses the disassembler, but is not part of the disassembler and should function without the disassembler.  In particular, it should show the nt, xt, flags, size, and a dump of the code (I'll comment more on this in native_words.asm)

2024-03-16 02:03 UTC, SamCoVT commented on native_words.asm
>                  sta base
`see` is not part of the disassembler (it's part of the TOOLS wordlist along with words like `.s`, `?`, `dump`, and `words`).  Without a disassembler, `see` should do everything it already does except for the jsr xt_disasm at the end (and the `2dup` before `dump`) a few lines above this comment (not sure why Github won't let me select lines that aren't near your changes to add comments to - it's your line 8474 abd 8476 that can go).  You can look at `see`'s output and decide whether or not to keep the `CR`.

2024-03-16 02:03 UTC, SamCoVT commented on native_words.asm
> +; ## SM_SLASH_REM ( d n1 -- n2 n3 ) "Symmetric signed division"
I'm always a fan of spelling mistakes.  I'm sure there's loads more - some are mine and some are not, but you're welcome to fix any you find.

2024-03-16 02:03 UTC, SamCoVT commented on platform/README.md
> +By default the top-level `make` will build `platform-py65mon.bin`.
This looks good.  While this is covered in the manual, I think it makes good sense to repeat it here for those that might be surfing the repo on GitHub - or the select few who actually open/read README files!

2024-03-16 02:03 UTC, SamCoVT commented on platform/platform-minimal.asm
> +; The 16K image leaves $f000-$ffff is empty other than py65mon I/O andthe interrupt vectors.
I think this reads best if you just remove the "is" from line 7, and you'll want a space in the middle of andthe.

Otherwise, I think this looks good, and a "small Tali2" is a question that has appeared multiple times on the forums and on GitHub.  You might want to mention that all a user has to do to port this for their system is to replace kernel_getc and kernel_putc with their own I/O.

2024-03-16 02:03 UTC, SamCoVT commented on platform/platform-py65mon.asm
> +;           |   Tali zp vars    |
Excellent followup on our "what on earth are user variables" discussion.

2024-03-16 02:03 UTC, SamCoVT commented on strings.asm
>  str_disasm_lit     = 13
`see`'s strings should remain, but the disassembler's strings can go.
Just be careful as these are offsets into the string_table below, so you can't delete items in the middle of the string_table below without somehow adjusting these.  The disasm strings at the end should be safe, though.

2024-03-16 02:03 UTC, SamCoVT commented on strings.asm
> +s_abc_lower:
Do we even need this at all?  I don't see it referenced anywhere.

2024-03-16 02:03 UTC, SamCoVT commented on strings.asm
> +s_wid_asm:
This looks like a reasonable way to solve the "I want to remove strings from the middle of the table".

2024-03-16 02:03 UTC, SamCoVT commented on strings.asm
>  s_disasm_lit: .text "LITERAL ", 0
`see`'s strings need to stay, but the disassembler strings can go.

2024-03-16 02:03 UTC, SamCoVT commented on strings.asm
> +es_allot:       .text "EALLT", 0
Can we have a different configuration word for doing error message shortening?  Perhaps "LONG_ERRORS" or something similar?  I'm open to suggestions for the configuration name, but I don't really like checking for an empty set and having extra "empty" behavior.

2024-03-16 02:03 UTC, SamCoVT commented on strings.asm
> +.if "environment?" in TALI_OPTIONAL_WORDS
I could have sworn I did this along with the `environment?` word as it's a word that virtually no-one will miss and it takes up gobs of space... and it looks like strings.asm was missed in that commit.  Good catch.

2024-03-16 02:03 UTC, SamCoVT commented on taliforth.asm
> +.if len(TALI_OPTIONAL_WORDS) > 0
If forth_words.asc is empty, does this really save anything?  I'd rather have a separate config word for doing this.  The user could also just comment out the lines in forth_code/forth_words.fs, but I could understand the appeal of a config setting to disable it all at once.  That config word could also prevent the `evaulate` in `cold` at the same time.

2024-03-16 02:12 UTC, SamCoVT commented
Also, just FYI, you don't need to resolve conflicts with generated files like the labelmap, listing, binary for py65mon, or test results - I will regenerate all of those while merging.  They are kept in the repo to help with troubleshooting so that I have the listing and labelmap that correspond to a given version and can do A-B testing, but they will always conflict if I push changes while you are working on a branch.

2024-03-16 10:58 UTC, patricksurry commented on native_words.asm
>                  sta base
ya that's a good point, i'll change that

2024-03-17 12:18 UTC, patricksurry commented on strings.asm
> +s_abc_lower:
will remove

2024-03-17 12:19 UTC, patricksurry commented on strings.asm
> +es_allot:       .text "EALLT", 0
I'm suggesting TALI_OPTION_TERSE in my update

2024-03-17 12:20 UTC, patricksurry commented on taliforth.asm
> +.if len(TALI_OPTIONAL_WORDS) > 0
It currently has a bunch of startup strings so this seemed easiest way to configure them out in this setup, unless orphisbin has some conditional processing?

2024-03-17 14:24 UTC, patricksurry commented on platform/platform-minimal.asm
> +; The 16K image leaves $f000-$ffff is empty other than py65mon I/O andthe interrupt vectors.
added that customization note

2024-03-17 14:30 UTC, patricksurry commented on strings.asm
>  str_disasm_lit     = 13
I used a variable to number these dynamically now which makes it easier to keep in sync.  lmk if that looks ok.

2024-03-17 14:35 UTC, patricksurry commented
I think I responded to all your comments, and resolved the obvious ones.  Others I left open with discussion above.  

Without removing `see` (which I agree is better) I needed to save a few more bytes to stay under 12K so I made ctrl-n/p history buffers configurable.  This also frees up the associated 1Kb of buffer RAM which will come in handy for my app.

The optional inclusion of forth_user_words is not ideal, but I couldn't see a better way of conditionally removing the startup strings there, since we want them to stay by default.   I could just note that config in the minimal platform file so people can decide if they want to undo it?

2024-03-17 21:12 UTC, SamCoVT commented
This all looks good.  I'm in the process of merging it now.  Just one note - if you are that close on bytes, Tali tends to drift in size by +/- 2kb or so, so there may come a time when this minimal platform file doesn't work anymore and there is no testing for that, so it will be a silent failure.  I see you've already added a warning if it overlaps the py65mon I/O.  I did also just merge your `s\"` improvements (including reduced size), so that gives you a bit of breathing room for now.  I think my plan is to not worry about it until someone complains about it.

You're welcome to add an extra word to allow `see` and its strings to be removed, but you'll have to open a new pull request if you want to do that.

I might go back and add a comment on what the `xi` business is doing in strings and maybe give that variable a clearer name - it looks like it could be confusing if you don't know what it's doing.  I do like that solution, though, as it allows items in the middle of the table to be removed and all the following strings shuffle up.

2024-03-17 21:19 UTC, merged

2024-03-17 21:19 UTC, patricksurry commented
I like having `see` there, so I'm fine with that.   Agree about the potentially silent failure - but hopefully that warning will at least give someone a clue what's going on.  If people end up using the minimal config we could start considering whether new features should be opted in or out of it to keep the size down.   But let's see if people use it.

I considering both lowering the start address and/or using non-default py65mon magic IO addresses higher in ROM (e.g. $ffxx instead of $f0xx) but the latter seems a bit of a barrier to beginner usage.  Also I like the idea of keeping under 12K within the top 16K of memory ($c000) since that's a kind of normal config someone might build hardware for.    Anyway, lots of options I guess.